/**
 * @file RatingStars.tsx
 * @module components/shop/RatingStars
 *
 * @description
 * Renders a compact 5-star visual rating alongside a review count badge.
 *
 * Stars are generated by mapping over the fixed array `[1, 2, 3, 4, 5]`.
 * Each star is filled when its position (`s`) is ≤ the **rounded** average
 * rating, giving a whole-star display (no half-stars).
 *
 * Returns `null` when `count === 0` so callers never see an empty star row.
 */

import { memo } from "react";
import { Star } from "lucide-react";

// ---------------------------------------------------------------------------
// Prop types
// ---------------------------------------------------------------------------

/**
 * Props accepted by {@link RatingStars}.
 */
interface RatingStarsProps {
  /**
   * Pre-computed average rating on a 0–5 scale.
   * E.g. `4.3` — rendered as 4 filled stars after rounding.
   */
  avg: number;
  /**
   * Total number of reviews that contributed to `avg`.
   * When `0` the component renders nothing.
   */
  count: number;
  /**
   * Visual size variant.
   * - `"sm"` (default) — used inside product cards.
   * - `"md"` — used on PDPs or larger contexts.
   * @default "sm"
   */
  size?: "sm" | "md";
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * 5-star rating strip with a `(count)` suffix.
 *
 * @remarks
 * Returns `null` (renders nothing) when `count` is zero, so parent
 * components don't need to guard against empty-rating scenarios.
 * Whole-star rounding is intentional: `Math.round(4.3)` → 4 filled stars.
 *
 * @param props - See {@link RatingStarsProps}.
 * @returns A flex row of `<Star>` icons and a count label, or `null`.
 *
 * @example
 * ```tsx
 * // Inside a product card, rating pre-fetched from useShopMetadata:
 * {rating && <RatingStars avg={rating.avg} count={rating.count} />}
 * ```
 */
const RatingStars = ({ avg, count, size = "sm" }: RatingStarsProps) => {
  // Early return: no reviews → render nothing (avoids empty star row)
  if (count === 0) return null;

  // Tailwind class string for the star icon size, responsive between breakpoints.
  const star = size === "sm" ? "w-3 h-3 md:w-3.5 md:h-3.5" : "w-4 h-4";

  return (
    <div className="flex items-center gap-1 mt-1">
      {/* Inner div holds the 5 star icons side-by-side without gap */}
      <div className="flex items-center">
        {/*
         * Map over [1, 2, 3, 4, 5] to render each star position.
         * A star at position `s` is "filled" (primary colour) when
         * s ≤ Math.round(avg). Otherwise it uses the muted/inactive style.
         */}
        {[1, 2, 3, 4, 5].map((s) => (
          <Star
            key={s}
            className={`${star} ${
              s <= Math.round(avg)
                ? "fill-primary text-primary"        // filled star
                : "text-muted-foreground/30"         // empty / inactive star
            }`}
          />
        ))}
      </div>

      {/*
       * Review count label, e.g. "(12)".
       * Intentionally small and muted so it doesn't compete with the price.
       */}
      <span className="text-[10px] md:text-xs text-muted-foreground">({count})</span>
    </div>
  );
};

/**
 * Memoised: rating data is identity-stable across renders, so this prevents
 * needless re-renders of 50+ instances inside a product grid.
 */
export default memo(RatingStars);
