project_id = "izeabmhtxtrelfqgkuua"

[functions.steadfast-webhook]
verify_jwt = false

[functions.inventory-sync]
verify_jwt = false

[functions.push-to-external-inventory]
verify_jwt = false

[functions.csp-report]
verify_jwt = false

[functions.security-scan]
verify_jwt = false



