/**
 * @file use-toast.ts
 * @module hooks/use-toast
 *
 * @description
 * A lightweight, framework-agnostic toast notification system built on top of
 * a module-level singleton store (no React context required).
 *
 * Architecture overview:
 *  - `memoryState`  – a single module-level `State` object holding the current
 *    list of toasts.  All mounted `useToast()` consumers share this object.
 *  - `listeners`    – an array of React `setState` callbacks; every `useToast()`
 *    consumer registers itself here on mount and deregisters on unmount.
 *  - `dispatch()`   – runs the pure `reducer` against `memoryState`, then fans
 *    the new state out to every listener, causing all consumers to re-render
 *    simultaneously.
 *  - `toastTimeouts`– a `Map` of pending `setTimeout` handles used to
 *    physically remove a toast from state after `TOAST_REMOVE_DELAY` ms
 *    (effectively keeping it in the DOM long enough for the exit animation).
 *
 * Constraints:
 *  - Only ONE toast is visible at a time (`TOAST_LIMIT = 1`).  Adding a new
 *    toast while one is active replaces it immediately.
 *  - Dismissed toasts are kept in state for `TOAST_REMOVE_DELAY` ms (~16 min)
 *    to allow CSS exit animations to complete, then removed via the
 *    `REMOVE_TOAST` action dispatched by a `setTimeout`.
 *
 * No network calls, no auth dependency, no localStorage usage.
 */

import * as React from "react";

import type { ToastActionElement, ToastProps } from "@/components/ui/toast";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Maximum number of toasts that can be held in state simultaneously.
 * Currently set to 1 — only the most recent toast is kept; older ones are
 * sliced off when `ADD_TOAST` is dispatched.
 */
const TOAST_LIMIT = 1;

/**
 * Delay (ms) before a dismissed toast is fully removed from state.
 * Set very high (~16 min) so CSS exit animations (which are typically
 * < 1 second) always have time to complete before the DOM node is removed.
 */
const TOAST_REMOVE_DELAY = 1000000;

// ---------------------------------------------------------------------------
// Core types
// ---------------------------------------------------------------------------

/**
 * Full runtime shape of a toast item held in the store.
 * Extends the base `ToastProps` from the UI component with required
 * identity (`id`) and optional rich content fields.
 */
type ToasterToast = ToastProps & {
  /** Unique identifier generated by `genId()`. */
  id: string;
  /** Heading rendered in bold at the top of the toast. */
  title?: React.ReactNode;
  /** Supporting text below the title. */
  description?: React.ReactNode;
  /** Optional action button rendered inside the toast. */
  action?: ToastActionElement;
};

/**
 * Discriminated union of all actions the toast reducer accepts.
 */
const actionTypes = {
  /** Push a new toast onto the front of the queue. */
  ADD_TOAST: "ADD_TOAST",
  /** Merge partial updates into an existing toast (by id). */
  UPDATE_TOAST: "UPDATE_TOAST",
  /**
   * Mark a toast (or all toasts if no id provided) as `open: false`,
   * triggering the exit animation, and schedule physical removal.
   */
  DISMISS_TOAST: "DISMISS_TOAST",
  /** Physically delete a toast from state after the exit animation window. */
  REMOVE_TOAST: "REMOVE_TOAST",
} as const;

/**
 * Module-level incrementing counter used to generate unique toast ids.
 * Wraps at `Number.MAX_SAFE_INTEGER` to avoid precision loss.
 */
let count = 0;

/**
 * Generates a unique, incrementing string id for each new toast.
 * Safe for the lifetime of a browser session — wraps at MAX_SAFE_INTEGER.
 *
 * @returns {string} A stringified integer id.
 */
function genId() {
  count = (count + 1) % Number.MAX_SAFE_INTEGER;
  return count.toString();
}

type ActionType = typeof actionTypes;

type Action =
  | {
      type: ActionType["ADD_TOAST"];
      toast: ToasterToast;
    }
  | {
      type: ActionType["UPDATE_TOAST"];
      /** Partial toast — only the provided fields are merged. */
      toast: Partial<ToasterToast>;
    }
  | {
      type: ActionType["DISMISS_TOAST"];
      /** If omitted, ALL active toasts are dismissed. */
      toastId?: ToasterToast["id"];
    }
  | {
      type: ActionType["REMOVE_TOAST"];
      /** If omitted, the entire toast list is cleared. */
      toastId?: ToasterToast["id"];
    };

/**
 * Shape of the module-level singleton toast store.
 */
interface State {
  /** Ordered list of active/animating toasts (newest first). */
  toasts: ToasterToast[];
}

// ---------------------------------------------------------------------------
// Module-level singleton store
// ---------------------------------------------------------------------------

/**
 * Map of `toastId → setTimeout handle`.
 * Used to guard against registering duplicate removal timers for the same
 * toast (e.g. if `DISMISS_TOAST` is fired multiple times for the same id).
 *
 * @sideEffects Entries are added by `addToRemoveQueue` and deleted when the
 * timeout fires, keeping the map size bounded by `TOAST_LIMIT`.
 */
const toastTimeouts = new Map<string, ReturnType<typeof setTimeout>>();

/**
 * Schedules the physical removal of a toast from state after
 * `TOAST_REMOVE_DELAY` ms.  The delay is long enough for any CSS exit
 * animation to complete.
 *
 * If a timer for `toastId` is already pending this is a no-op (idempotent).
 *
 * @param toastId - The id of the toast to schedule for removal.
 *
 * @sideEffects
 *  - Adds an entry to `toastTimeouts`.
 *  - Fires `dispatch({ type: "REMOVE_TOAST", ... })` after the delay.
 */
const addToRemoveQueue = (toastId: string) => {
  // Guard: do not register a second timer for the same toast.
  if (toastTimeouts.has(toastId)) {
    return;
  }

  const timeout = setTimeout(() => {
    // Cleanup the map entry so the id could theoretically be reused.
    toastTimeouts.delete(toastId);
    dispatch({
      type: "REMOVE_TOAST",
      toastId: toastId,
    });
  }, TOAST_REMOVE_DELAY);

  toastTimeouts.set(toastId, timeout);
};

// ---------------------------------------------------------------------------
// Reducer
// ---------------------------------------------------------------------------

/**
 * Pure reducer for the toast store.
 *
 * Exported primarily for unit-testing — components should use `useToast()`
 * or the imperative `toast()` function instead.
 *
 * @param state  - Current toast state.
 * @param action - Discriminated union action to apply.
 * @returns      New state (always a fresh object reference).
 *
 * @sideEffects
 *  `DISMISS_TOAST` triggers `addToRemoveQueue()` as a side-effect inside the
 *  reducer (acknowledged as a deliberate design compromise — see inline note).
 */
export const reducer = (state: State, action: Action): State => {
  switch (action.type) {
    case "ADD_TOAST":
      // Prepend the new toast and cap the list to TOAST_LIMIT (currently 1).
      return {
        ...state,
        toasts: [action.toast, ...state.toasts].slice(0, TOAST_LIMIT),
      };

    case "UPDATE_TOAST":
      // Merge partial fields into the matching toast; leave others unchanged.
      return {
        ...state,
        toasts: state.toasts.map((t) => (t.id === action.toast.id ? { ...t, ...action.toast } : t)),
      };

    case "DISMISS_TOAST": {
      const { toastId } = action;

      // ! Side effects ! - This could be extracted into a dismissToast() action,
      // but I'll keep it here for simplicity
      if (toastId) {
        // Schedule removal for the specific toast.
        addToRemoveQueue(toastId);
      } else {
        // No id supplied → dismiss every active toast.
        state.toasts.forEach((toast) => {
          addToRemoveQueue(toast.id);
        });
      }

      // Set `open: false` to trigger the exit animation in the UI component.
      return {
        ...state,
        toasts: state.toasts.map((t) =>
          t.id === toastId || toastId === undefined
            ? {
                ...t,
                open: false,
              }
            : t,
        ),
      };
    }
    case "REMOVE_TOAST":
      // Physically delete the toast from state (called after animation delay).
      if (action.toastId === undefined) {
        // No id → wipe the entire list.
        return {
          ...state,
          toasts: [],
        };
      }
      return {
        ...state,
        toasts: state.toasts.filter((t) => t.id !== action.toastId),
      };
  }
};

// ---------------------------------------------------------------------------
// Singleton store wiring
// ---------------------------------------------------------------------------

/**
 * All currently mounted `useToast()` consumers register their `setState`
 * callback here.  `dispatch` fans new state out to every entry, keeping all
 * consumers in sync without a React context.
 */
const listeners: Array<(state: State) => void> = [];

/**
 * The single source of truth for toast state at the module level.
 * Shared across all components that call `useToast()`.
 */
let memoryState: State = { toasts: [] };

/**
 * Applies `action` to `memoryState` via the `reducer` and notifies all
 * registered `listeners`.
 *
 * @param action - The action to dispatch.
 *
 * @sideEffects Updates `memoryState` in-place and calls every listener.
 */
function dispatch(action: Action) {
  memoryState = reducer(memoryState, action);
  listeners.forEach((listener) => {
    listener(memoryState);
  });
}

// ---------------------------------------------------------------------------
// Public imperative API
// ---------------------------------------------------------------------------

/**
 * Shape of a toast before it has been assigned an id by the store.
 * Callers pass this to the imperative `toast()` function.
 */
type Toast = Omit<ToasterToast, "id">;

/**
 * Imperative function to fire a toast notification from anywhere in the app
 * (including outside React components, e.g. in async utilities or route
 * loaders) without needing to call `useToast()`.
 *
 * @example
 * ```ts
 * import { toast } from "@/hooks/use-toast";
 * toast({ title: "Saved!", description: "Your changes have been saved." });
 * ```
 *
 * @param props - Toast content and variant props (excluding `id`).
 * @returns An object with:
 *   - `id`      — the generated toast id (useful for targeted updates/dismissal).
 *   - `dismiss` — call to close this specific toast immediately.
 *   - `update`  — call to merge new props into the toast while it is visible.
 *
 * @sideEffects Dispatches `ADD_TOAST` to the singleton store, which
 *   synchronously updates `memoryState` and notifies all listeners.
 */
function toast({ ...props }: Toast) {
  const id = genId();

  // Convenience updater bound to this toast's id.
  const update = (props: ToasterToast) =>
    dispatch({
      type: "UPDATE_TOAST",
      toast: { ...props, id },
    });

  // Convenience dismisser bound to this toast's id.
  const dismiss = () => dispatch({ type: "DISMISS_TOAST", toastId: id });

  dispatch({
    type: "ADD_TOAST",
    toast: {
      ...props,
      id,
      open: true,
      // Auto-dismiss when the Radix UI primitive closes (e.g. swipe-away).
      onOpenChange: (open) => {
        if (!open) dismiss();
      },
    },
  });

  return {
    id: id,
    dismiss,
    update,
  };
}

// ---------------------------------------------------------------------------
// React hook
// ---------------------------------------------------------------------------

/**
 * React hook that subscribes a component to the singleton toast store and
 * exposes both the current toast list and the `toast` / `dismiss` helpers.
 *
 * Multiple components can safely call `useToast()` — they all share the same
 * underlying `memoryState` and re-render together whenever it changes.
 *
 * @example
 * ```tsx
 * const { toast } = useToast();
 * // Later, in an event handler:
 * toast({ title: "Copied to clipboard" });
 * ```
 *
 * @returns {object}
 *   - `toasts`  – current array of `ToasterToast` objects (read-only display).
 *   - `toast`   – imperative function to show a new toast (see `toast()` above).
 *   - `dismiss` – `(toastId?: string) => void` — dismisses a specific toast or
 *                 all toasts if called without arguments.
 *
 * @sideEffects
 *  - Pushes `setState` into the module-level `listeners` array on mount.
 *  - Splices `setState` out of `listeners` on unmount, preventing stale
 *    callbacks from causing state updates on unmounted components.
 */
function useToast() {
  // Bootstrap local state from the current singleton snapshot so the component
  // renders the right toasts even before the next dispatch fires.
  const [state, setState] = React.useState<State>(memoryState);

  React.useEffect(() => {
    // Register this component's setState as a listener.
    listeners.push(setState);

    // Cleanup: remove this listener when the component unmounts.
    return () => {
      const index = listeners.indexOf(setState);
      if (index > -1) {
        listeners.splice(index, 1);
      }
    };
  }, [state]); // Re-registering on state change keeps the closure fresh.

  return {
    // Spread the current state (exposes `toasts` array).
    ...state,
    // Expose the imperative toast creator.
    toast,
    // Dismiss helper bound to the dispatch function.
    dismiss: (toastId?: string) => dispatch({ type: "DISMISS_TOAST", toastId }),
  };
}

export { useToast, toast };
