/**
 * @file types.ts
 * @description Shared types, constants, and factory functions for the bulk-product
 * admin feature (Add Products panel + Edit Products panel + CSV import).
 *
 * ── Key concepts ──────────────────────────────────────────────────────────────
 *
 * ProductRow / VariantRow
 *   Pure UI state shapes; they are NOT the Supabase DB row types.  Extra fields
 *   (`id`, `expanded`, `_dbId`, `_dirty`) are UI-only and stripped before any
 *   Supabase write.
 *
 * id vs _dbId
 *   `id`    — a client-side temporary key generated by `generateId()` (random
 *             8-char base-36 string).  Used as React `key` prop.  Never sent to DB.
 *   `_dbId` — the real UUID from Supabase.  Present on rows loaded from the DB
 *             in useBulkEditProducts; undefined on new rows in useBulkAddProducts.
 *
 * _dirty flag
 *   Set to `true` by `updateEditProduct` / `updateEditVariant` whenever the admin
 *   changes any field.  `saveEditedProducts` in useBulkEditProducts only sends
 *   UPDATE queries for rows where `_dirty === true`, avoiding redundant writes.
 *
 * sizes / colors (string fields)
 *   Stored as comma-separated strings in the UI (e.g. "S, M, L").
 *   Converted to `string[]` via `.split(",").map(s => s.trim()).filter(Boolean)`
 *   before being written to the Supabase `sizes` / `colors` jsonb array columns.
 *
 * BATCH_SIZE
 *   Products are inserted in batches of 25 to stay well within Supabase's
 *   default row-insert limits per request and to allow smooth progress reporting.
 *   Variants use a secondary inner batch size of 100 (lighter payload).
 *
 * EDIT_PAGE_SIZE
 *   The edit panel paginates client-side after loading all products into memory.
 *   20 rows per page keeps the DOM light when editing large catalogues.
 */

/** A single product variant row (size × colour combination). */
export interface VariantRow {
  /** Client-side temporary key (never sent to DB). */
  id: string;
  /** Size string, e.g. "M", '54"'. Empty string = no size. */
  size: string;
  /** Colour string, e.g. "Black". Empty string = no colour. */
  color: string;
  /** Available stock units for this specific variant. */
  stock: number;
  /** Optional SKU / barcode string for inventory tracking. */
  sku: string;
  /**
   * Price delta relative to the parent product price.
   * 0 = same price; positive = premium; negative = discount.
   */
  price_adjustment: number;
  /** Optional Cloudinary (or any CDN) URL for a variant-specific image. */
  image_url: string;
  /**
   * Real Supabase UUID from `product_variants.id`.
   * Undefined for newly added variants that haven't been saved yet.
   */
  _dbId?: string;
}

/** A product row as it exists in the bulk-add/edit UI state. */
export interface ProductRow {
  /** Client-side temporary key (React key prop, never sent to DB). */
  id: string;
  /** Product display name — required for validation. */
  name: string;
  /** Category name string — must match an existing category. */
  category: string;
  /** Regular (non-sale) price in BDT (৳). Required, must be > 0. */
  price: number;
  /** Active sale price in BDT (৳); null means no sale. */
  sale_price: number | null;
  /** Total available stock units (across all variants if any). */
  stock: number;
  /** Long-form product description (Markdown supported). */
  description: string;
  /** Fabric/material name (e.g. "Nida", "Zoom"). */
  material: string;
  /**
   * Comma-separated sizes string, e.g. 'S, M, L, 54"'.
   * Converted to string[] before DB writes.
   */
  sizes: string;
  /**
   * Comma-separated colours string, e.g. "Black, White, Navy".
   * Converted to string[] before DB writes.
   */
  colors: string;
  /** Whether this product appears in the "featured" section of the storefront. */
  featured: boolean;
  /** Primary product image URL (Cloudinary or direct CDN URL). */
  image_url: string;
  /** Variant rows for this product. */
  variants: VariantRow[];
  /** Whether the expanded detail section (description, variants) is visible. */
  expanded: boolean;
  /**
   * Real Supabase UUID from `products.id`.
   * Undefined for rows not yet saved to the DB (add mode).
   */
  _dbId?: string;
  /**
   * Dirty flag — set to true by any field update in edit mode.
   * `saveEditedProducts` only UPDATEs rows with `_dirty === true`.
   */
  _dirty?: boolean;
}

/** Aggregated results returned after a bulk-add submit. */
export interface SubmitResults {
  /** Number of products successfully inserted. */
  success: number;
  /** Number of products that failed to insert (Supabase error). */
  failed: number;
  /** Total variant rows successfully inserted. */
  variants: number;
  /** Human-readable error messages, one per failed batch. */
  errors: string[];
}

/**
 * Generates a lightweight client-side temporary ID.
 * Uses Math.random().toString(36) — NOT cryptographically secure;
 * only used as a React `key` prop, never stored in the DB.
 *
 * @returns 8-character base-36 string, e.g. "k7x9a2bc".
 */
export const generateId = () => Math.random().toString(36).slice(2, 10);

/**
 * Creates a blank ProductRow with a fresh temporary id.
 * Used by `addProducts(n)` in useBulkAddProducts to initialise new rows.
 *
 * @returns A fully-typed empty ProductRow.
 */
export const createEmptyProduct = (): ProductRow => ({
  id: generateId(),
  name: "", category: "", price: 0, sale_price: null, stock: 0,
  description: "", material: "", sizes: "", colors: "",
  featured: false, image_url: "", variants: [], expanded: false,
});

/**
 * Creates a blank VariantRow with a fresh temporary id.
 * Used by `addVariant(productId)` in both useBulkAddProducts and useBulkEditProducts.
 *
 * @returns A fully-typed empty VariantRow.
 */
export const createEmptyVariant = (): VariantRow => ({
  id: generateId(), size: "", color: "", stock: 0, sku: "", price_adjustment: 0, image_url: "",
});

/**
 * Common sizes for Bangladeshi modest-fashion garments.
 * Includes both numeric inch sizes (borka/abaya) and standard S-XXL.
 */
export const COMMON_SIZES = ['50"', '52"', '54"', '56"', '58"', '60"', "S", "M", "L", "XL", "XXL", "Free Size"];

/** Common colour names used across the product catalogue. */
export const COMMON_COLORS = ["Black", "White", "Navy", "Maroon", "Grey", "Beige", "Brown", "Red", "Green", "Blue", "Purple", "Pink"];

/** Common fabric/material types for modest-fashion garments sold on the platform. */
export const COMMON_MATERIALS = ["Nida", "Zoom", "Jorjet", "Chiffon", "Silk", "Cotton", "Linen", "Crepe", "Satin"];

/**
 * Maximum number of product rows sent in a single Supabase INSERT call.
 * Keeping this at 25 avoids request timeouts and enables smooth progress-bar
 * updates between batches during large bulk-add operations.
 */
export const BATCH_SIZE = 25;

/**
 * Number of products shown per page in the Edit Products panel.
 * Client-side pagination after a full load; 20 rows keeps rendering fast.
 */
export const EDIT_PAGE_SIZE = 20;
